"""Add index to user_id in orders table

Revision ID: 08f43bcdd9a2
Revises: 9ddde3c77625
Create Date: 2025-02-18 16:19:52.819945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f43bcdd9a2'
down_revision: Union[str, None] = '9ddde3c77625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_index('ix_orders_id', table_name='orders')
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
