"""Add restaurant_id to orders

Revision ID: 0e407ee70bc2
Revises: 459eb660f242
Create Date: 2025-02-20 13:04:21.710489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e407ee70bc2'
down_revision: Union[str, None] = '459eb660f242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'])
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('restaurants', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint('restaurants_user_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_constraint('restaurants_order_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'order_id')
    op.drop_column('restaurants', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_order_id_fkey', 'restaurants', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('restaurants_user_id_fkey', 'restaurants', 'users', ['user_id'], ['id'])
    op.alter_column('restaurants', 'location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'restaurant_id')
    # ### end Alembic commands ###
